### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by ghost** [monostable/footwork#1]
Please clarify the license for source code in this repo. Is it ok to assume (A)GPLv3+?

**Comment by kasbah** [comment]
Thanks for pointing it out! I had forgotten to `git add` the MIT license.
 
I am glad you are taking an interest in this but it the code, as it is, an undocumented mess and there are a lot of unused files where I was just learning Racket or pursuing a dead end. Please don't hesitate to get in touch if you need any clarification on anything.
